### ISSUE TITLE
Pilas engine 3D

### ISSUE THREAD

**Issue by kone9** [pilas-engine/pilas-engine#10]
Hola he visto que pilas engine es muy practico tiene un diseño excelente para aprender a programar y practicar con python..Tambien vi que hay una version en web que es pilas 2....Me gustaria saber si hay posibilidades de poder usar todos esas clases de metodos y funciones en juegos 3D....Habiendo game engine como unity,unreal,incluso godot engine,veo que ninguno esta tan orientado al publico en español..ya que PILAS ENGINE esta completamente en español...Es una excelente idea que tendria que poder usarse en juegos 3D....Obviamente no sofistivcados como los de AAA pero algo se podria a hacer con python por el tema del rendimiento...Soy usuario de Blender3D hace 6 años si les interesa la propuesta cuenten conmigo.Saludos.

**Comment by kone9** [comment]
Me encantaria que exista un motor completamente en español para desarrollar videojuegs...te paso un proyecto de arquitectura visualización que hice con godot engine y Blender3D.
https://www.youtube.com/watch?v=nrzrS9xgjUA

**Comment by hugoruscitti** [comment]
Hola @kone9, gracias por tu aporte!!! Efectivamente estamos trabajando en la versión 2 de pilas-engine, pero adoptando un enfoque diferente: estamos haciéndolo funcionar en la web tanto de forma online como offline, con un editor propio y una interfaz de usuario más sencilla, que fomente el "descubrimiento" incluso para quienes abren el editor sin siquiera tener una idea básico de código.

Escribí algo de este enfoque en mi blog:

http://examplelab.com.ar/comenzamos-pilas-engine-2/

y voy contando el desarrollo en el mismo readme del proyecto:

https://github.com/pilas-engine/pilas-engine

Ahora bien, no sé si podremos llegar a abordar algo como desarrollo de juegos 3D, ¡es bastante complejo!!.

No lo descarto a futuro igualmente, creo que primero vamos a tener que avanzar bastante en que la versión 2 funcione bien, y luego ver si es posible incorporar algo de 3D.

Voy a cerrar el issue por el momento, pero sentite libre de seguir comentando. Me gusta la idea, pero quisiera abordarla mucho más adelante.

**Comment by kone9** [comment]
OK,gracias.entonces tendremos que esperar,Actualmente me parece que no existe un game engine completamente 3D que no utilize exporter para juegos web,osea que sea javascript puro para trabajar en web con 3D.El unico que conosco es BLEND4web pero es de pago o no esta tan orientado a videojuegos a parte esta todo en ingles...Gracias por responder me encantaria poder aportar algo,pero por ahora no tengo mucho conocimiento.Apenas tenga algo de conocimiento al respecto veo si puedo hacer un aporte o abrir una rama del pilas 2 pero en 3D.Saludos

**Comment by hugoruscitti** [comment]
Excelente @kone9, voy a darle un vistazo a algunas bibliotecas javascript a ver si alguna nos facilita algo de 3D mientras tanto. Charlemos más adelante!, algo vamos a poder hacer con 3D en el futuro.

**Comment by kone9** [comment]
Te paso unos tips de Blender3D 2.8 para que los tengas en cuenta..
-Blender3D puede exportar en un formato que se llama GLTF 2.0 supuestamente este formato exporta texturas animaciones y mallas(tambien esta fbx).
-Se pueden tomar mallas basicas para crear modelos parecidos a los ejemplos de pilas engine pero en 3D.
.Una cosa muy interesante que conoci con GODOT ENGINE es que cada escena es un objeto.OSEA QUE vos podes tener una escena principal ,dentro otra escena que sea el avion y el avion puede instanciar escenas de balas,las balas puede ser editadas independientemente porque cada objeto es una escena...Si miras la documentación de godot engine capas te interesa ese diseño para una interface.
Ya no te quito más tiempo.Saludos.

**Comment by hugoruscitti** [comment]
Dale, lo voy a investigar y "maquinar un poco" sobre cómo podríamos pensar una implementación a futuro.

Saludos!

**Comment by kone9** [comment]
Te paso este game engine dice que es online y de codigo abierto,pero el editor no lo es(no entiendo esoXD)...Yo siempre hago pruebas con godot engine en web y deja bastante que desear y .sobre todo las ultimas versiones....Te paso el link para que veas los ejemplos y el rendimiento que tienen en web....
Que bueno poder hablar con alguien en español..Todo github esta en ingles.
https://playcanvas.com/explore/featured

**Comment by kone9** [comment]
Una página en español que habla al respecto sobre el game engine play canvas...https://gamedevelopment.tutsplus.com/es/tutorials/create-a-space-shooter-with-playcanvas-part-1--cms-28066

**Comment by kone9** [comment]
github de playcanvas parece que es open source https://github.com/playcanvas/engine pero esta completamente en ingles
