### ISSUE TITLE
Poner el modo oscuro por omisión al abrir el editor por primera vez

### ISSUE THREAD

**Issue by kone9** [pilas-engine/pilas-engine#13]
Me parece que el modo oscuro es mucho más visible y fácil de usar,por eso pienso que tendria que ser el color por defecto.
![2019-04-14 17_19_58-](https://user-images.githubusercontent.com/12847027/56099858-15582580-5ee9-11e9-966e-84aed779f2ee.jpg)

**Comment by hugoruscitti** [comment]
Es una buena idea, a mí también me parece mejor el modo oscuro. Lo que no me convence mucho hasta ahora es cómo se ven los iconos en el modo oscuro. Con algunos íconos apliqué in efecto de inversión de colores, pero con los iconos que tienen muchos colores queda muy raro...

Estoy investigando cómo hacen otros IDEs para resolver eso. Si encontrás alguna guía o ideas sobre eso avisame!!!

De todas formas, coincido con tu observación, voy a poner por omisión el modo oscuro en una próxima versión.

**Comment by kone9** [comment]
> Es una buena idea, a mí también me parece mejor el modo oscuro. Lo que no me convence mucho hasta ahora es cómo se ven los iconos en el modo oscuro. Con algunos íconos apliqué in efecto de inversión de colores, pero con los iconos que tienen muchos colores queda muy raro...
> 
> Estoy investigando cómo hacen otros IDEs para resolver eso. Si encontrás alguna guía o ideas sobre eso avisame!!!
> 
> De todas formas, coincido con tu observación, voy a poner por omisión el modo oscuro en una próxima versión.

A mi me encanta el editor como esta...Lo que podrías hacer es agregar tooltips arriba de los iconos para saber que significa cada cosa,entonces si los iconos son medios feos,"por ahora",la gente que lo usa puede saber que esta haciendo....
Definitivamente creo que te conviene copiar a unity,ya que la mayoría de las personas que usan los game engine usan UNITY,por lo tanto una interface parecida atraería a mucha gente...Y como veo la interface tiene algo de unity y algo de godot.

Godot usa unos íconos medios raros-
pero estan diferenciados por color...
por ejemplo para 2D se usan iconos azules,para 3D de colores medio naranja,para label o textos usan colores verdes y aunque los iconos sean raros los colores ayudan a determinar para que son cada cosa
![2019-04-14 21_11_36-Godot Engine - FlappyBird3D - MenuPrincipal tscn](https://user-images.githubusercontent.com/12847027/56101424-f910b480-5ef9-11e9-8ad6-d5fc4df9ca3e.jpg)

Blender últimamente opto por iconos del mismo color a mi no me gusta mucho eso
![2019-04-14 21_12_41-Blender](https://user-images.githubusercontent.com/12847027/56101457-42f99a80-5efa-11e9-9220-092b328ccddc.jpg)

Unity3D directamente no usa iconos.
![2019-04-14 21_15_01-Unity 2018 3 2f1 Personal - main unity - FlappyBird - PC, Mac   Linux Standalone](https://user-images.githubusercontent.com/12847027/56101473-73413900-5efa-11e9-9cf2-26d01b6bd0a6.jpg)

Si queres hago unos iconos 3D renderzidos con blender3D personalizados y de paso conosco más a fondo pilas...
