### ISSUE TITLE
Agregar API de física para cambiar la aceleración gravitatoria de la escena.

### ISSUE THREAD

**Issue by hugoruscitti** [pilas-engine/pilas-engine#15]
Al implementar esto, ver la posibilidad de agregar estos controles de gravedad al inspector de propiedades de la escena.

También revisar que la gravedad se defina por escena, y no de forma global en todo el proyecto.

Nota: este feature se conversó inicialmente en el foro de pilas http://foro.pilas-engine.com.ar/t/gravedad-en-pilas2/1640/2

**Comment by kone9** [comment]
Si es posible prepararlo para cuando agreguemos las librerias 3D.
Claro es una propiedad de la escena en si,pero hay objetos que usan las físicas y otras no....Por eso godot engine tiene nodos especiales y supuestamente optimizados para manejar la física de forma separada,aunque capas eso no encaja con el diseño de pilas2...

**Comment by hugoruscitti** [comment]
Ahí agregué la posibilidad de cambiar la gravedad de cada escena desde el inspector de la escena y desde el código. Acá hay un ejemplo de cómo utilizarlo:

https://app-dev.pilas-engine.com.ar/#/ejemplos/gravedad

y la documentación detallando cómo se llaman las funciones para manipular la gravedad:

- https://app-dev.pilas-engine.com.ar/manual/escenas.html#gravedad-y-simulaci%C3%B3n-f%C3%ADsica

En particular, este ejemplo:

```
pilas.fisica.gravedad_x = 1;
pilas.fisica.gravedad_y = 1;
```
