### ISSUE TITLE
No puedo ejecutar “make iniciar” para el entorno de trabajo con pilas 

### ISSUE THREAD

**Issue by kone9** [pilas-engine/pilas-engine#16]
Hola estoy siguiendo los pasos de este video.
https://www.youtube.com/watch?v=ASKYT7OoLos

Sin embargo al escribir make iniciar no funciona dice command not found
alguien sabe por que dice eso la terminal.Aquí hay un screenshot
![2019-04-17 10_13_49-MINGW64__c_Users_ariel_Desktop_estudio y desarrollo  de pilas engine 3D_pilas-en](https://user-images.githubusercontent.com/12847027/56292233-2b3e3400-60fd-11e9-9c13-baaca7af59e4.jpg)
El sistema operativo que estoy usando es windows 7 64 bits.
la versión de node es 10.15.0
Tambien instale el gestor de paquetes "yarn"

**Comment by kone9** [comment]
"MAKE" es un comando de linux...alguien sabe cuales serian los comandos en windows  para ejecutar el repositorio o alguna terminal que pueda emular comandos de linux en windows7
![2019-04-17 11_00_46-Windows PowerShell](https://user-images.githubusercontent.com/12847027/56293863-51190800-6100-11e9-89ab-c575af311288.jpg)

**Comment by hugoruscitti** [comment]
Buenas @kone9, tengo entendido que en windows se puede utilizar este proyecto para tener algo muy parecido a un terminal de linux con los comandos de gnu: https://www.cygwin.com/

Hace un tiempo también usé git bash, creo que también traía make instalando, pero no estoy muy seguro. Por las dudas te paso el link: https://gitforwindows.org/

**Comment by kone9** [comment]
> Buenas @kone9, tengo entendido que en windows se puede utilizar este proyecto para tener algo muy parecido a un terminal de linux con los comandos de gnu: https://www.cygwin.com/
> 
> Hace un tiempo también usé git bash, creo que también traía make instalando, pero no estoy muy seguro. Por las dudas te paso el link: https://gitforwindows.org/


Ok.si instale cygwin y solape todo al momento de la instalación,sobre todo lo que decía "MAKE".

![fIAPf](https://user-images.githubusercontent.com/12847027/56301292-e7075f80-610d-11e9-8718-79d7a0bc06c5.png)

después de eso ya pude ejecutar el comando "MAKE" en windows 7
![2019-04-17 12_29_24-_cygdrive_c_Users_ariel_Desktop_estudio y desarrollo  de pilas engine 3D_pilas-e](https://user-images.githubusercontent.com/12847027/56301345-01d9d400-610e-11e9-9733-fa80e16c84fb.jpg)
![2019-04-17 12_35_48-_cygdrive_c_Users_ariel_Desktop_estudio y desarrollo  de pilas engine 3D_pilas-e](https://user-images.githubusercontent.com/12847027/56301348-07371e80-610e-11e9-9cfa-e081cc877bfe.jpg)
![2019-04-17 12_40_58-PilasEngine](https://user-images.githubusercontent.com/12847027/56301385-1a49ee80-610e-11e9-9e9a-003a647a697e.jpg)

**Comment by kone9** [comment]
> Buenas @kone9, tengo entendido que en windows se puede utilizar este proyecto para tener algo muy parecido a un terminal de linux con los comandos de gnu: https://www.cygwin.com/
> 
> Hace un tiempo también usé git bash, creo que también traía make instalando, pero no estoy muy seguro. Por las dudas te paso el link: https://gitforwindows.org/

Apenas tengo un poco de tiempo hago un tutorial al respecto,creo que es algo muy común y hay poca documentación o nada en español

**Comment by hugoruscitti** [comment]
Estoy ordenando un poco los issues con etiquetas @kone9, voy a cerrar este issue por el momento. Si vez que quedó algo afuera escribime y lo abro de nuevo.

**Comment by kone9** [comment]
> Estoy ordenando un poco los issues con etiquetas @kone9, voy a cerrar este issue por el momento. Si vez que quedó algo afuera escribime y lo abro de nuevo.

OK,gracias.
