### ISSUE TITLE
Imagen de docker para version 2.x

### ISSUE THREAD

**Issue by humitos** [pilas-engine/pilas-engine#28]
Hola! Acabo de actualizar las imágenes de Docker que he venido usando para los talleres. Hoy publiqué una nueva imagen que ejecuta la nueva versión 2.x de pilas-engine.

Este comando debería ser suficiente para tener pilas corriendo localmente en http://localhost:4200/

```bash
docker run -it --rm -p '4200:4200' --device /dev/snd humitos/pilas-engine:latest
```

Espero que les sirva. No sabía dónde comentar esto así que abrí un issue, pero lo pueden cerrar cuando estén notificados.

El repositorio está en https://github.com/humitos/pilas-engine

> Además, hay una nueva versión para la imagen anterior (pilas-engine 1.4.12) que incluye la configuración necesaria para utilizar el sonido

**Comment by hugoruscitti** [comment]
Gracias @humitos !!!, voy a agregar links en los readme de los dos proyectos así pueden acceder a los dockerfile. Mil gracias!
