### ISSUE TITLE
¿Puedo llamar a las bibliotecas de note.js en el motor Pilas?

### ISSUE THREAD

**Issue by streetartist** [pilas-engine/pilas-engine#38]
No sé si las bibliotecas en note.js pueden ser llamadas en el motor Pilas, así que pregunté.

**Comment by hugoruscitti** [comment]
Hola @streetartist !!, se puede llamar nodejs directamente pero dependen de dónde se esté ejecutando
pilas. Por ejemplo, en la versión offline de pilas se utiliza [electron](https://www.electronjs.org/) así que sí
se puede llamar a módulos de nodejs desde ahí. Sin embargo, cuando pilas se ejecuta dentro de un editor
como chrome o firefox no puede acceder directamente a nodejs. La única forma de interactuar con node.js, python
u otra plataforma es mediante una API.
