### ISSUE TITLE
Sugerencia para clonar el proyecto.

### ISSUE THREAD

**Issue by ks7000** [pilas-engine/pilas-engine#6]
Con el debido respeto les escribo para _sugerir_ , en el archivo "README.md" el colocar

`git clone https://github.com/pilas-engine/pilas-engine.git`

en vez de

`git clone git@github.com:pilas-engine/pilas-engine.git`

porque ahora github es "https" un certificado público y bien conocido.

Me disculpan la molestia, para nosotros los usuarios que estamos siempre aprendiendo es útil siempre el camino más sencillo, ¡gracias por vuestra atención! 🤓

(si consigo algo más importante, hago una bifurcación "fork" y les aviso _a ver si les es útil_).

**Comment by hugoruscitti** [comment]
Oh, es muy buena sugerencia!!! Ahí lo corregí @ks7000 !!! gracias!!!
