### ISSUE TITLE
Problemas con la ejecución de pilas-engine 2.0|

### ISSUE THREAD

**Issue by statick88** [pilas-engine/pilas-engine#9]
Saludos, quería reportar este inconveniente, quizá no sea nada del otro mundo pero le puede estar pasando a otros

```
statick@localhost:~/proyectos/pilas-engine$ sudo make iniciar
[sudo] password for statick: 

- Iniciando el proyecto.
▷ Instalando dependencias. 
npm ERR! path /home/statick/proyectos/pilas-engine/node_modules/npm/node_modules/dezalgo/node_modules/asap
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/statick/proyectos/pilas-engine/node_modules/npm/node_modules/dezalgo/node_modules/asap' -> '/home/statick/proyectos/pilas-engine/node_modules/npm/node_modules/dezalgo/node_modules/.asap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-01T06_50_45_261Z-debug.log
Makefile:75: fallo en las instrucciones para el objetivo 'iniciar'
make: *** [iniciar] Error 254
```
```
statick@localhost:~/proyectos/pilas-engine$ sudo make ejecutar
▷ Iniciando ember s 
yarn start
yarn run v1.5.1
$ ember server
Cannot find module 'npm-registry-client'


Stack Trace and Error Report: /tmp/error.dump.0cb3d6149deda72bc19d3ce9640d8de7.log
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c ember server
Directory: /home/statick/proyectos/pilas-engine
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/statick/proyectos/pilas-engine/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:92: fallo en las instrucciones para el objetivo 'serve'
make: *** [serve] Error 1
statick@localhost:~/proyectos/pilas-engine$ less /tmp/error.dump.0cb3d6149deda72bc19d3ce9640d8de7.log 
```
El contenido del log dice lo siguiente

`  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/statick/proyectos/pilas-engine/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

=================================================================================
`

**Comment by statick88** [comment]
El log completo del error

`=================================================================================

ENV Summary:

  TIME: Sun Apr 01 2018 06:55:21 GMT+0000 (UTC)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /home/statick/proyectos/pilas-engine/node_modules/.bin/ember
  - server
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/statick/proyectos/pilas-engine/node_modules/.bin
  - /usr/local/share/.config/yarn/link/node_modules/.bin
  - /home/statick/proyectos/pilas-engine/node_modules/.bin
  - /usr/local/share/.config/yarn/link/node_modules/.bin
  - /usr/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/lib/node_modules/npm/bin/node-gyp-bin
  - /usr/bin/node_modules/npm/bin/node-gyp-bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  PLATFORM: linux x64
  FREEMEM: 2742534144
  TOTALMEM: 8163594240
  UPTIME: 7420
  LOADAVG: 0.84228515625,0.890625,0.9072265625
  CPUS:
  - Intel(R) Core(TM) i7 CPU       U 640  @ 1.20GHz - 1200
  - Intel(R) Core(TM) i7 CPU       U 640  @ 1.20GHz - 666
  - Intel(R) Core(TM) i7 CPU       U 640  @ 1.20GHz - 666
  - Intel(R) Core(TM) i7 CPU       U 640  @ 1.20GHz - 799
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.13.0
  - cldr: 32.0.1
  - http_parser: 2.8.0
  - icu: 60.2
  - modules: 59
  - napi: 2
  - nghttp2: 1.29.0
  - node: 9.10.1
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.2
  - v8: 6.2.414.46-node.23
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'npm-registry-client'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'npm-registry-client'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/statick/proyectos/pilas-engine/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

=================================================================================`

**Comment by hugoruscitti** [comment]
Hola @5t4t1ck !!, nunca probé ejecutando make iniciar con "sudo". ¿Será que el problema viene por ahí?.

¿podrías probar borrando las dependencias y empezando de nuevo?. Tendrías que borrar los directorios con este comando:

```
sudo rm -rf node_modules tmp dist
```

Por cierto, si quisiera reproducir el mismo sistema que tenes vos, ¿que tendría que instalar?, ¿es debian?

**Comment by statick88** [comment]
Este tema ya se resolvió en la wiki de instalación agregue los pasos necesarios para una instalación sin problemas https://github.com/hugoruscitti/pilas/wiki/instalacion
